$(document).ready(function(){
    InitFunc();
    SaveThemeCookie();
    ThemeSetFunc();
    NavFunc();
    SearchButtonFunc();
    ConsolePostOpenEditFunc();
    ConsolePostOpenDetailFunc();
    ConsoleAddPostFunc();
    ConsoleControlPostFunc();
    BackTopFunc();
    ConsolePageFunc();
    ConsoleTypeFunc();
})
