$(document).ready(function(){
    InitFunc();
    SaveThemeCookie();
    ThemeSetFunc();
    NavFunc();
    PostOpenDetailFunc();
    SearchButtonFunc();
    PermissionButtonFunc();
    PageFunc();
    EditPostFunc();
})